export const QK = {
  branches: ['branches'] as const,
  branch: (id: string) => ['branches', id] as const,
  products: ['products'] as const,
  product: (id: string) => ['products', id] as const,
  productByCode: (code: string) => ['products', 'barcode', code] as const,
  customers: ['customers'] as const,
  employees: ['employees'] as const,
  suppliers: ['suppliers'] as const,
  transactions: ['transactions'] as const,
  leads: ['leads'] as const,
  invoices: ['invoices'] as const,
  aiInsights: ['ai', 'insights'] as const,
  payrollRuns: ['payroll', 'runs'] as const,
  stockMovements: ['stock', 'movements'] as const,
  leaveRequests: ['hr', 'leave-requests'] as const,
  purchaseOrders: ['purchase-orders'] as const,
  notifications: ['notifications'] as const,
  chama: ['chama'] as const,
  chamaGroup: (id: string) => ['chama', id] as const,
  etimsStatus: (invoiceId: string) => ['etims', invoiceId] as const,
};
