import type { Role } from '../types';

/**
 * Capability ACL — granular permissions over and above role-based access.
 *
 * Roles are convenience defaults. Anyone with `users.grant` (owner/director
 * by default) can grant or revoke individual capabilities per user. This is
 * how a manager gets "add staff" rights without becoming a full director.
 */
export const CAPABILITIES = [
  // Navigation (mirrors PERMISSION_MATRIX paths for UI use)
  'nav:/',
  'nav:/pos',
  'nav:/inventory',
  'nav:/crm',
  'nav:/customers',
  'nav:/accounting',
  'nav:/payroll',
  'nav:/hr',
  'nav:/employees',
  'nav:/suppliers',
  'nav:/branches',
  'nav:/reports',
  'nav:/analytics',
  'nav:/ai',
  'nav:/settings',
  'nav:/chama',

  // POS
  'pos.sell',
  'pos.refund',
  'pos.void',
  'pos.discount.custom',
  'pos.shift.open',
  'pos.shift.close',
  'pos.cash.drop',
  'pos.cash.payout',

  // Inventory + products
  'products.read',
  'products.create',
  'products.update',
  'products.delete',
  'inventory.read',
  'inventory.adjust',
  'inventory.transfer',
  'inventory.recount',

  // Customers + CRM
  'customers.read',
  'customers.create',
  'customers.update',
  'customers.delete',
  'crm.read',
  'crm.write',
  'crm.assign',

  // Accounting + invoicing
  'accounting.read',
  'accounting.write',
  'accounting.approve',
  'invoices.create',
  'invoices.send',
  'invoices.cancel',
  'invoices.write_off',

  // Payroll + HR
  'payroll.read',
  'payroll.run',
  'payroll.approve',
  'payroll.disburse',
  'hr.read',
  'hr.write',
  'hr.leave.approve',
  'hr.discipline',

  // Employees
  'employees.read',
  'employees.create',
  'employees.update',
  'employees.terminate',

  // Suppliers + POs
  'suppliers.read',
  'suppliers.write',
  'purchaseorders.create',
  'purchaseorders.approve',
  'purchaseorders.receive',

  // Branches
  'branches.read',
  'branches.create',
  'branches.update',
  'branches.close',

  // Reporting + analytics
  'reports.view',
  'reports.export',
  'analytics.view',
  'analytics.export',

  // AI
  'ai.use',
  'ai.admin',

  // Settings + identity
  'settings.read',
  'settings.write',
  'settings.billing',
  'settings.integrations',
  'users.read',
  'users.invite',
  'users.update',
  'users.deactivate',
  'users.grant',
  'roles.read',
  'roles.assign',
  'roles.create',

  // Chama (group money)
  'chama.read',
  'chama.write',
  'chama.approve',
  'chama.disburse',

  // Tax / payments compliance
  'etims.file',
  'etims.cancel',
  'mpesa.stk',
  'mpesa.b2c',
  'mpesa.reconcile',
] as const;

export type Capability = (typeof CAPABILITIES)[number];

/** Default capability set per role. Owners can grant/revoke per user. */
export const ROLE_CAPS: Record<Role, ReadonlyArray<Capability>> = {
  super_admin: CAPABILITIES,
  admin: CAPABILITIES,
  owner: CAPABILITIES,
  director: CAPABILITIES.filter((c) => c !== 'settings.billing') as Capability[],
  ceo: CAPABILITIES.filter((c) => c !== 'settings.billing') as Capability[],

  branch_manager: [
    'nav:/',
    'nav:/pos',
    'nav:/inventory',
    'nav:/crm',
    'nav:/customers',
    'nav:/employees',
    'nav:/suppliers',
    'nav:/reports',
    'nav:/analytics',
    'nav:/ai',
    'nav:/chama',
    'pos.sell',
    'pos.refund',
    'pos.void',
    'pos.discount.custom',
    'pos.shift.open',
    'pos.shift.close',
    'pos.cash.drop',
    'products.read',
    'products.update',
    'inventory.read',
    'inventory.adjust',
    'inventory.transfer',
    'customers.read',
    'customers.create',
    'customers.update',
    'crm.read',
    'crm.write',
    'crm.assign',
    'employees.read',
    'employees.update',
    'suppliers.read',
    'suppliers.write',
    'purchaseorders.create',
    'purchaseorders.approve',
    'purchaseorders.receive',
    'reports.view',
    'reports.export',
    'analytics.view',
    'ai.use',
    'chama.read',
    'chama.write',
    'etims.file',
    'mpesa.stk',
    'mpesa.reconcile',
  ],

  supervisor: [
    'nav:/',
    'nav:/pos',
    'nav:/inventory',
    'nav:/crm',
    'nav:/customers',
    'nav:/employees',
    'nav:/reports',
    'nav:/ai',
    'nav:/chama',
    'pos.sell',
    'pos.refund',
    'pos.void',
    'pos.discount.custom',
    'pos.shift.open',
    'pos.shift.close',
    'pos.cash.drop',
    'products.read',
    'inventory.read',
    'inventory.adjust',
    'customers.read',
    'customers.create',
    'customers.update',
    'employees.read',
    'reports.view',
    'ai.use',
    'etims.file',
    'mpesa.stk',
  ],

  accountant: [
    'nav:/',
    'nav:/accounting',
    'nav:/payroll',
    'nav:/customers',
    'nav:/suppliers',
    'nav:/reports',
    'nav:/analytics',
    'nav:/ai',
    'accounting.read',
    'accounting.write',
    'accounting.approve',
    'invoices.create',
    'invoices.send',
    'invoices.cancel',
    'invoices.write_off',
    'payroll.read',
    'payroll.run',
    'payroll.approve',
    'customers.read',
    'suppliers.read',
    'reports.view',
    'reports.export',
    'analytics.view',
    'ai.use',
    'etims.file',
    'etims.cancel',
    'mpesa.reconcile',
  ],

  inventory_manager: [
    'nav:/',
    'nav:/inventory',
    'nav:/suppliers',
    'nav:/reports',
    'nav:/ai',
    'products.read',
    'products.create',
    'products.update',
    'inventory.read',
    'inventory.adjust',
    'inventory.transfer',
    'inventory.recount',
    'suppliers.read',
    'suppliers.write',
    'purchaseorders.create',
    'purchaseorders.receive',
    'reports.view',
    'ai.use',
  ],

  hr_manager: [
    'nav:/',
    'nav:/hr',
    'nav:/payroll',
    'nav:/employees',
    'nav:/reports',
    'nav:/ai',
    'hr.read',
    'hr.write',
    'hr.leave.approve',
    'hr.discipline',
    'employees.read',
    'employees.create',
    'employees.update',
    'employees.terminate',
    'payroll.read',
    'payroll.run',
    'reports.view',
    'reports.export',
    'ai.use',
  ],

  sales_agent: [
    'nav:/',
    'nav:/pos',
    'nav:/crm',
    'nav:/customers',
    'nav:/ai',
    'pos.sell',
    'pos.shift.open',
    'pos.shift.close',
    'customers.read',
    'customers.create',
    'customers.update',
    'crm.read',
    'crm.write',
    'ai.use',
  ],

  cashier: [
    'nav:/',
    'nav:/pos',
    'nav:/customers',
    'pos.sell',
    'pos.shift.open',
    'pos.shift.close',
    'customers.read',
    'customers.create',
  ],

  employee: ['nav:/', 'nav:/ai', 'ai.use'],
};
